### ISSUE TITLE
/compose/image don't work

### ISSUE THREAD

**Issue by 1aristotelis** [pow-co/pow.co#13]
https://user-images.githubusercontent.com/8962092/217213762-bf4464ce-f420-40d0-aed6-4fa7efe19baf.mov

There might be 2 issues in 1: 

- first is how to image is stored to the blockchain (does not render on whatsonchain https://whatsonchain.com/tx/5f790d22f8503dcc69567a3eb8da7018e12c8b7fc08cd33ea170835e0e7d7b59)
- The redirect page (to /[txid].tsx) renders "undefined" for content_tx

**Comment by 1aristotelis** [comment]
fixed by commit 0d84fb29fb3790f666ccdf33172ca21fca5c5975

**Comment by derrickhorton** [comment]
Wow, cool!
