### ISSUE TITLE
Add Composer at Top of Topic Page Feed

### ISSUE THREAD

**Issue by stevenzeiler** [pow-co/pow.co#144]
Example: pow.co/topics/worldbuilder (or pow.co/t/worldbuilder ?) would allow you to post new content, URLs, images, etc.

The current compose component shall be added at the top of the topic-specific feed.

When constructing the transaction it should use a BMAP attribute called "channel" set to "worldbuilder" similar to how bitchat messages also include that BMAP "channel" attribute.

**Comment by usselman** [comment]
Closed thanks to @GuiDeMa !
