### ISSUE TITLE
Markdown URLs don't go off-site

### ISSUE THREAD

**Issue by usselman** [pow-co/pow.co#21]
In this post: https://pow.co/9d30eaa493c42c904987cd1c27f2f8a2d2ed5c2627c67c70f30bcf990f5757ca , I am using a markdown URL to take people to my personal website. But instead of taking you to `shirish.neocities.org` it takes you to `pow.co/shirish.neocities.org`.

**Comment by derrickhorton** [comment]
Oh, interesting issue! Thank you for making me aware of this. This might be something I can fix.

**Comment by derrickhorton** [comment]
Following up, I noticed a discrepancy where: 

A URL starting with `www.` goes to `https://pow.co/www.<URL>`

A URL starting with `https://` goes to `<URL>`

<img width="641" alt="Screenshot 2023-02-15 at 21 43 33" src="https://user-images.githubusercontent.com/4019818/219157670-505a24d5-e415-4883-a39b-056e91770bbc.png">
<img width="365" alt="Screenshot 2023-02-15 at 21 43 11" src="https://user-images.githubusercontent.com/4019818/219157680-b3898ede-a619-4f35-971e-25f4229cd7f1.png">
<img width="573" alt="Screenshot 2023-02-15 at 21 44 14" src="https://user-images.githubusercontent.com/4019818/219157685-bc400bad-b13e-4430-83f9-95a5a0257da5.png">
<img width="325" alt="Screenshot 2023-02-15 at 21 44 24" src="https://user-images.githubusercontent.com/4019818/219157689-d7dd4887-0abb-4a0a-8ee9-bdb3d08c172e.png">


Example video:


https://user-images.githubusercontent.com/4019818/219157740-94e29cb9-a9ef-4110-ae21-82e50ad4b5fd.mp4

**Comment by usselman** [comment]
That's interesting. I believe the issue may be happening here, on lines 105 through 121 of OnChainEvent.tsx

For some reason, `www.` gets concatenated onto your URL while `https://` actually replaces it with the link.

<img width="842" alt="Screen Shot 2023-02-15 at 1 49 15 PM" src="https://user-images.githubusercontent.com/19578049/219176727-c159a852-5848-472f-80b6-84195a2c9fcc.png">

**Comment by 1aristotelis** [comment]
@eddiewillers @usselman latest commit fixes this
