### ISSUE TITLE
Powco daily meeting not accessible directly from the URL

### ISSUE THREAD

**Issue by DanielKrawisz** [pow-co/pow.co#32]
When we go to pow.co/meet the daily meeting never loads properly. It only loads if you go to the main page and then click the link to the daily meeting. Why???? 

The meeting should load reliably from the url and the link.

**Comment by DanielKrawisz** [comment]
Staking 211 pow co tokens.

**Comment by eddiewillers** [comment]
@DanielKrawisz Can this be closed?
