### ISSUE TITLE
Hovering over "txid" should give you a tooltip linking to Proof of Work Playtime episode explaining it.

### ISSUE THREAD

**Issue by usselman** [pow-co/pow.co#35]
I am copying over [Issue #59](https://github.com/pow-co/old.pow.co/issues/59) from old.pow.co and I have solved it by creating a tooltip that takes the user to a link explaining txids from learnmeabitcoin.com.

I will create a branch and push the update. 
I humbly ask for a 150 pow.co token bounty - 100 for myself and 50 for @1ielvis for helping me understand onClick events bubbling up.

**Comment by derrickhorton** [comment]
@usselman @ielvisd 

I rise to your request for tokens once the Pull Request is merged closing this issue.

🥇 150 POWCO 🥇

**Comment by usselman** [comment]
@eddiewillers @ielvisd 
I look forward to this bounty being fulfilled!

**Comment by derrickhorton** [comment]
🥇
