### ISSUE TITLE
Mobile YouTube Links (m.youtube.com) Fail to Load as Playable on Site

### ISSUE THREAD

**Issue by derrickhorton** [pow-co/pow.co#45]
Regular YouTube links display as playable on pow.co

However, when shared via the mobile app (m.youtube.com) the link does not appear as a playable video.

Example (top playable, bottom not playable):

<img width="506" alt="Screenshot 2023-03-01 at 11 43 25" src="https://user-images.githubusercontent.com/4019818/222117313-5808d338-33c8-4e79-a8ef-4f21fe73f3d3.png">

**Comment by 1aristotelis** [comment]
fixed
