### ISSUE TITLE
/api not found

### ISSUE THREAD

**Issue by 1aristotelis** [pow-co/pow.co#49]
This affects the following pages
-  /twetch
- /profile/[twetch_paymail]

And twetch login.

I did not have this issue running the project in dev mode.  It might have something to do with how the project is exported and run on the prod server
@owenkellogg any insight ?

**Comment by stevenzeiler** [comment]
The nginx web server routes all traffic under pow.co/api to another back end api process running the boostpow api

**Comment by 1aristotelis** [comment]
possible to reroute traffic under pow.co/api/v1 to boostpow api ? and leave pow.co/api to nextjs app?

**Comment by GuiDeMa** [comment]
Twetch is down right now we are missing on a great opportunity

**Comment by stevenzeiler** [comment]
You cannot use /api because nginx is set to serve swagger API documentation on that route.
