### ISSUE TITLE
powstream.com video page needs a boost button. 

### ISSUE THREAD

**Issue by DanielKrawisz** [pow-co/pow.co#5]
When I watch a video on powstream.com, I don't see a boost button anywhere. There needs to be a boost button in an obvious location.

Example: https://powstream.com/video/KI2Pt4qS-8Q 

There is no repo for powstream that I could find so I posted this issue here.

**Comment by eddiewillers** [comment]
@DanielKrawisz is this now completed to your satisfaction?
