### ISSUE TITLE
Boosted BitChats do not render correctly

### ISSUE THREAD

**Issue by usselman** [pow-co/pow.co#55]
For example, I boosted this chat message: [txid](https://whatsonchain.com/tx/76fd84fecf2bcb40016f66e6c94213fbdf6628d4078b5ac31942be5a1c2914a2)

<img width="538" alt="Screen Shot 2023-03-07 at 9 47 41 PM" src="https://user-images.githubusercontent.com/19578049/223629818-e9fab7e5-36fd-4465-9d08-3b003b8242dd.png">

**Comment by 1aristotelis** [comment]
fake news !!
