### ISSUE TITLE
URL Share Bar Not Showing on Firefox

### ISSUE THREAD

**Issue by stevenzeiler** [pow-co/pow.co#95]
Works on Brave but not FF desktop oddly![b8404d6159ef191bf99a75a61281955fec4a67f05dde2e1d2578a1915d082c30.png](https://user-images.githubusercontent.com/508282/232314626-3711d3aa-8a63-45b7-8501-6290e320d97a.png)

**Comment by 1aristotelis** [comment]
you have to be logged in to see the share URL bar. I just tested it on firefox desktop and it is present.
